### ISSUE TITLE
TypeError using garmin.py default mode

### ISSUE THREAD

**Issue by cypg09** [jat255/fit_file_uploader#3]
**Description:**

Hi! First, thank you for building this tool; it solves a problem I encounter too. However, I encountered an error when trying to use it in default mode.

**Steps to Reproduce:**

1. Run the command:
   ```
   python3 garmin.py ../../indieVelo/{private indieVelo ID}/FITFiles/{private indieVelo ID}_20241018_160553_c.fit
   ```

**Expected Behavior:**

The script should process the file without errors.

**Actual Behavior:**

The script throws a `TypeError`. Here's the error message:

```
[19:44:35] INFO     Activity timestamp is "2024-10-18T18:05:56"     garmin.py:85
Traceback (most recent call last):
  File "/Users/{my username}/indieVelo2garmin/fit_file_uploader/garmin.py", line 218, in <module>
    output_path = edit_fit(p)
  File "/Users/{my username}/indieVelo2garmin/fit_file_uploader/garmin.py", line 86, in edit_fit
    print_message(f"Record: {i}", message)
  File "/Users/{my username}/indieVelo2garmin/fit_file_uploader/garmin.py", line 54, in print_message
    man = Manufacturer(message.manufacturer).name if message.manufacturer in Manufacturer else "BLANK"
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/enum.py", line 397, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumMeta'
```

**Environment:**

- Python version: 3.9.6 
- Operating System: macOS 15.1 

**Additional Information:**

Any ideas on how to solve this? Thank you!

**Comment by jat255** [comment]
Sorry for the delay getting back to you. If you don't mind sharing, can you upload the fit file you're having issues with? That would let me take a closer look

**Comment by jat255** [comment]
@cypg09 are you still seeing this error? If so, would you be able to supply a file that was causing the problem?

**Comment by tsvoronos** [comment]
Hello, I'm having a very similar looking issue. Zipped fit file attached, errors below:

```
[12:08:51] INFO     Activity timestamp is "2024-12-30T12:31:00"                                                                                                                                           garmin.py:85
Traceback (most recent call last):
  File "/Users/{username}/fit_file_uploader-main/garmin.py", line 218, in <module>
    output_path = edit_fit(p)
  File "/Users/{username}/fit_file_uploader-main/garmin.py", line 86, in edit_fit
    print_message(f"Record: {i}", message)
  File "/Users/{username}/fit_file_uploader-main/garmin.py", line 54, in print_message
    man = Manufacturer(message.manufacturer).name if message.manufacturer in Manufacturer else "BLANK"
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/enum.py", line 397, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumMeta'
```

[8EA9BC3F36715B97_20241230_173059_c.fit.zip](https://github.com/user-attachments/files/18286084/8EA9BC3F36715B97_20241230_173059_c.fit.zip)

**Comment by jat255** [comment]
@tsvoronos thanks for the example file. I'll try to take a look at this in the next few days to see what's going on.

**Comment by tsvoronos** [comment]
Thank you! I have managed to get things working; I believe my initial attempts were not using python in my virtual environment. On Jan 2, 2025, at 10:45 AM, Joshua Taillon ***@***.***> wrote:﻿
@tsvoronos thanks for the example file. I'll try to take a look at this in the next few days to see what's going on.

**Comment by jat255** [comment]
@cypg09 I see in your traceback you're using Python 3.9, which seems likely to be where the error is coming from. Can you upgrade to a more modern python version (I developed this on 3.12) using homebrew or pyenv and try again?

**Comment by jat255** [comment]
Closing this to clean things up. @cypg09, feel free to re-open the issue if this is still an issue for you after upgrading to 3.12
